### ISSUE TITLE
Broken Faucet - Chapter 4: Play Money 

### ISSUE THREAD

**Issue by T0admomo** [learn-ocean/ocean-academy#104]
Chapter 4 of Ocean Academy uses a broken faucet and Ocean has its own running ocean faucet 
https://faucet.rinkeby.oceanprotocol.com/

And here is an alternative Chainlink/ETH faucet that could be used as well 
https://faucets.chain.link/rinkeby

**Comment by MeMent0L** [comment]
Hi @T0admomo, thank you for the notice. We are aware of the issues with the official rinkeby and will be pushing a fix shortly (moving to the LINK faucet). Let us know if you would like to get involved in Ocean Academy! We are setting ourselves as a DAO, and always looking for good team members...

**Comment by MeMent0L** [comment]
This was fixed with the _SeaFire_ release from February 2022

**Comment by MeMent0L** [comment]
This was fixed with the SeaFire release from February 2022
