### ISSUE TITLE
Uncaught TypeError when starting new coursework as new/ unknown user

### ISSUE THREAD

**Issue by DOling** [learn-ocean/ocean-academy#119]
When I start a new course as a new/unknown user, I get the following error message:

![image](https://user-images.githubusercontent.com/24934801/155890781-93fe15eb-b74c-4ef8-8b9e-517263f646a1.png)

The screen stays black and I am not redirected to the content of the first chapter.
![image](https://user-images.githubusercontent.com/24934801/155891251-f52b5f5b-baf7-47bc-b24d-738ec9e55a55.png)

**Comment by MeMent0L** [comment]
Thanks for reporting here, you're right. Not sure what the issue is, perhaps @mwmouawad will be able to help?

**Comment by mwmouawad** [comment]
Hello @DOling thank you very much for your message! I am sorry for the delay, was on vacation for a couple of days. So I have solved the bug, you may see it here:  #121. Please check if you see any other errors, it is really great to have user's feedback to spot those bugs :)
