### ISSUE TITLE
How do I run this code locally?

### ISSUE THREAD

**Issue by SarahKay99** [learn-ocean/ocean-academy#12]
Hi,

Sorry if this is a rookie question, but what commands do I use in terminal to run this site locally? There is nothing in the Readme.

**Comment by SarahKay99** [comment]
After running `npm install` and `yarn install`, I ran `npm start` and got this outcome:

![image](https://user-images.githubusercontent.com/51705696/98367884-7d9dc780-208a-11eb-9e71-37a8e5b63c0d.png)

the `yarn start` outcome is here: 

![image](https://user-images.githubusercontent.com/51705696/98368004-b0e05680-208a-11eb-93f9-c98be23d9bd1.png)

(I changed PORT to SET PORT because I'm on Windows)

**Comment by oceanByte** [comment]
Setup instructions were included in https://github.com/learn-ocean/ocean-academy/pull/15
