### ISSUE TITLE
Open new tab when clicking link

### ISSUE THREAD

**Issue by oceanByte** [learn-ocean/ocean-academy#17]
Currently, when you click on a link in the chapters it opens in the same tab as the application.

It would enhance the user experience if a new tab would open when you click on a link.

**Comment by Harshith2255** [comment]
Hi
I would like to do contribute to this project.could you assign me.

**Comment by Harshith2255** [comment]
I cant find the html file which contains these links.
could you help me out?

**Comment by oceanByte** [comment]
> I cant find the html file which contains these links.
> could you help me out?

We use markdown (md) files which get rendered to HTML. You can find all chapters here: 
`ocean-academy/src/frontend/src/pages/Chapters/ChapterX/course.md`
Where X is the number of the chapter. The file containing the content is always `course.md`

**Comment by Harshith2255** [comment]
I am unable to clone the repository
it is showing this message
The authenticity of host 'github.com (13.234.176.102)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Host key verification failed.

**Comment by Harshith2255** [comment]
no problem it has been resolved

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/24

Thanks for your pull request! @Harshith2255 feel free to join our community: https://t.me/joinchat/H5DpbhgUGuRb8iqi-lp9Og

**Comment by Harshith2255** [comment]
thank you
