### ISSUE TITLE
Chapter validation does not reset 

### ISSUE THREAD

**Issue by oceanbyte-deprecated** [learn-ocean/ocean-academy#18]
Reproduction: Go to any chapter (except chapter one) and select the correct answer. Submit the answer. Click "previous chapter" and then click "next chapter". Now you should be in the same chapter where you started. Submit the answer without selecting an answer. Validation will be successful though it should be wrong.

See video for a visual explanation: https://youtu.be/oDN7fBc5IKI

It seems like the selection does not reset when you change the chapter.

**Comment by learn-ocean** [comment]
Fixed
