### ISSUE TITLE
Replace Left-Hand Chapter Menu with Module Menu 

### ISSUE THREAD

**Issue by SarahKay99** [learn-ocean/ocean-academy#19]
Since we are adding new modules, we need to have a way of displaying them. 
Currently the website is configured to display chapters, not modules.

Solving this problem would require refactoring our (on site) database. Please share any ideas or contributions here.

**Comment by oceanByte** [comment]
We are currently using this Figma board to explore ideas: https://www.figma.com/file/If6wwgh7KLKNYMOJzPXx31/OceanAcademy.io?node-id=0%3A1

**Comment by SarahKay99** [comment]
This is part of Project Shrimp now:
![image](https://user-images.githubusercontent.com/51705696/103045539-0344ea80-45d9-11eb-8487-6dabda7e66ee.png)

**Redesign of Left Menu**

- [ ] Refactor data. This is also part of #43 so see that issue for the reward bounty.
- [ ] Create UI with React. Reward: ?
- [ ] Hook up to UI to data. Reward: ?

Overall reward allocation: ?

@oceanByte

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/57
