### ISSUE TITLE
Rename 'master' to 'main' branch

### ISSUE THREAD

**Issue by oceanbyte-deprecated** [learn-ocean/ocean-academy#21]
We consider ourselves an inclusive project and we should not use terms like "master" since this is an offensive term, as it can be interpreted as being slavery-origin terminology. See https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns

To avoid offensive terminology and to avoid further inconsistency (other big projects adopted this terminology already) and follow the current recommended practices by GitHub we should switch to "main" as our primary branch.

> "Both Conservancy and the Git project are aware that the initial branch name, ‘master’, is offensive to some people and we empathize with those hurt by the use of that term.
> 
> Existing versions of Git are capable of working with any branch name; there's nothing special about ‘master’ except that it has historically been the name used for the first branch when creating a new repository from scratch (with the git init command). Thus many projects use it to represent the primary line of development. We support and encourage projects to switch to branch names that are meaningful and inclusive, and we'll be adding features to Git to make it even easier to use a different default for new projects.
> 
> As a first step, Git will add a mechanism to allow users to specify the default used as the name of the first branch when creating a new repository. Also, consistent with its project governance, Git has undertaken a community process to explore changing the name of the first branch created automatically for new repositories away from ‘master’. That change is currently being discussed on our mailing list. As always, changes in Git's core will minimize disruption for Git's users and will include appropriate deprecation periods.
> 
> Meanwhile, Git as a project remains engaged in encouraging participation of underrepresented groups in the development of Git itself. Git continues their participation, which began four years ago, in Conservancy's Outreachy initiative. Conservancy also continues to explore and support other initiatives that can also assist in this area." 

Source: https://sfconservancy.org/news/2020/jun/23/gitbranchname/

**Comment by oceanByte** [comment]
I created the `main` branch. @learn-ocean can you delete the `master` and set `main` as our default branch?

**Comment by learn-ocean** [comment]
Done in 49b79c357a6bea2b3f53008fba406e3c77f08fa4
