### ISSUE TITLE
Add animation for background

### ISSUE THREAD

**Issue by oceanByte** [learn-ocean/ocean-academy#26]
Our current background on all pages but the chapter pages contains four colored lines (a static SVG). The new oceanprotocol.com page contains the same lines but they are animated (changing amplitude).

I suggest the same or similar animation for the Ocean Academy. Animations add to the experience of an "interactive experience" that we want to convey.

**Comment by kaimeinke** [comment]
I absolutely love it. I guess the OCEAN team would love to have it too. ;)

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/33
