### ISSUE TITLE
Mark finished chapters in the sidebar using an icon

### ISSUE THREAD

**Issue by oceanByte** [learn-ocean/ocean-academy#28]
We already save the progress of a user and in the "account" page (e.g. https://oceanacademy.io/user/oceanbyte) and we show the progress of the user there: 
![image](https://user-images.githubusercontent.com/75223088/100984360-ef164c00-354a-11eb-9938-d2791938a1bf.png)

We should use the same icons to show progress in the sidebar. It improves the user experience because it 1) increases motivation and 2) it helps with orientation ("I don't remember exactly which chapter I finished yesterday").

**Comment by MeMent0L** [comment]
Fixed a long time ago, closing.
