### ISSUE TITLE
Development doesn't work on Windows

### ISSUE THREAD

**Issue by SarahKay99** [learn-ocean/ocean-academy#32]
![image](https://user-images.githubusercontent.com/51705696/101278591-5f092880-3810-11eb-83e0-420b52c8f5b3.png)
This is the error I get when I run "npm start" on my Windows machine. The error persists when I change all my ports to 8080. I recall it might be a syntax problem with Windows.

**Comment by MeMent0L** [comment]
If i remember well @learn-ocean mentioned that the stack worked only in Linux or Mac, no?

**Comment by oceanByte** [comment]
Fixed with https://github.com/learn-ocean/ocean-academy/pull/45
