### ISSUE TITLE
Optimise chapter validation UX

### ISSUE THREAD

**Issue by lopezi** [learn-ocean/ocean-academy#34]
related to: #25 

As a user of the ocean protocol academy on smaller computer screens, I would like to be able to access the Chapter Validation module without having to scroll.

Furthermore, as a new user, I would like to see the validation module and immediately understand the application wants me to validate the answer in that specific area. (because, without seen the module, I could associate the "Next chapter" button has the validation button by itself - which is, per se, something to explore)

![validation](https://user-images.githubusercontent.com/388476/101639068-c4cefd80-3a26-11eb-8494-92a0e004eded.jpg)

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/35
