### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by oceanByte** [learn-ocean/ocean-academy#41]
The current readme is 1) incomplete (missing links (Figma, Trello, proposal(s)), sections describing the architecture of the project are completely missing) and 2) difficult to follow (the how-to-contribute section could be simplified). 

- [x] Add missing links
- [x] Simplify how-to-contribute section
- [x] Fix typos and grammar

**Comment by SarahKay99** [comment]
#42 for simplifying the how-to-contribute section

**Comment by oceanByte** [comment]
> #42 for simplifying the how-to-contribute section

Reviewed. This looks much better! 

I will take care of creating the other sections and I'll invite you to review them then.

**Comment by oceanByte** [comment]
Merged with https://github.com/learn-ocean/ocean-academy/pull/57
