### ISSUE TITLE
Chapter 24 appears blank

### ISSUE THREAD

**Issue by lopezi** [learn-ocean/ocean-academy#62]
Chapter 24 of module Ocean101 appears blank after completion of the previous 23 chapters.

![unknown1](https://user-images.githubusercontent.com/388476/107577067-e34da280-6be9-11eb-98c9-da4b9e808f2c.png)

**Comment by oceanByte** [comment]
Fixed with https://github.com/learn-ocean/ocean-academy/commit/1330978080f7be3517503a4e58eb218ffaa205cc
