### ISSUE TITLE
101 chapter 15: error in quiz exploration

### ISSUE THREAD

**Issue by fr-3deric** [learn-ocean/ocean-academy#72]
The exploration in chapter 15 is wrong:

Which one of these statements is false?

Expected behaviour:
[ ] Every asset on Ocean Protocol has its own DID
[x] A DID is a JSON object with information about the Asset
[ ] A DDO is a string representing the data attributes

Current behaviour:
[ ] Every asset on Ocean Protocol has its own DID
[ ] A DID is a JSON object with information about the Asset
[x] A DDO is a string representing the data attributes

**Comment by MeMent0L** [comment]
This was fixed with the _Sea Fire_ release in Feb 2022.
