### ISSUE TITLE
101 chapter 15: content incorrect

### ISSUE THREAD

**Issue by fr-3deric** [learn-ocean/ocean-academy#73]
The info in chapter 15 about where metadata is stored seems to be incorrect:

"The metadata is stored in a store called Aquarius." 
-> that's partly true. Aquarius is a metadata cache, that fetches metadata from chain, caches it and serves it to the market. Metadata is stored on-chain.

"As we said earlier the metadata itself is never stored on-chain. Aquarius, the metadata store handles the actual documents while only DIDs are stored on-chain."
-> same here. DID, DDO and the data assets URL (encrypted) are stored on-chain. This is done by issuing a transaction to the metadata smart contract that contains the following fields: create{DID,{dataTokenAddress, encrypted[URL], DDO}, optional}.

**Comment by MeMent0L** [comment]
This was fixed with the _Sea Fire_ release in Feb 2022
