### ISSUE TITLE
Let the user choose the sharing URL path

### ISSUE THREAD

**Issue by 0xNoe** [learn-ocean/ocean-academy#76]
Hi !

Currently, the "Certified URL" option uses the user ID to define the path. If someone signs up with a nickname, the URL allowing them to share their certificate with other people (or put it on linkedin) will end with their nickname.
The problem is that the user at the time of registration is not aware of this. And that he might have preferred to have a more "professional" sharing URL for his certificate, in his name.

It might be interesting to add an option to solve this problem. It would be nice if before the certificate is awarded, the user is asked how they want their link to end. For example "How do you want your certificate sharing link to end ?"
Or warn the user before registering that the pseudonym they have chosen will be used for the sharing URL.

**Comment by MeMent0L** [comment]
Users will be able to edit their name and email with the _School Of Fish_ release in June 2022
