### ISSUE TITLE
Error in Discord link on main page

### ISSUE THREAD

**Issue by nslotus** [learn-ocean/ocean-academy#88]
On the main page there are two tabs, get started and join the community. When "joining the community" takes you to Discord, it is the old/incorrect account. 

Also final sentence in the paragraph, "Anyone who successfully completes Ocean 101 can go on to become and Ocean Ambassador." Should read "an Ambassador".

**Comment by MeMent0L** [comment]
This was fixed with the SeaFire release from February 2022
